# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [[ -d ".vim/bundle/vim-manpager" ]]; then
 export MANPAGER='zsh -c "vim -MRn -c \"set ft=man nomod nolist nospell nonu\" \
   -c \"nm q :qa!<CR>\" -c \"nm <end> G\" -c \"nm <home> gg\"</dev/tty <(col -b)"' 
fi

# system specific stuff
SYSTYPE=$(uname)

# mac os x specific stuff
if [[ $SYSTYPE == "Darwin" ]]; then
  # Homebrew specific
  if [ -d "$HOME/Developer/homebrew/bin" ]; then
    PATH="$HOME/Developer/homebrew/bin:$HOME/bin:$PATH"
    # vimversion=$(ls -r $HOME/Developer/homebrew/Cellar/vim | head -n 1)
    # export VIMRUNTIME="$HOME/Developer/homebrew/Cellar/vim/${vimversion}/share/vim/vim80"
    [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh
  fi
  
  # Subversion
  svn="$HOME/Developer/svn"

  # Aliases
  alias plx='plutil -convert xml1 -o -'
  alias cdrep="cd $HOME/Library/AutoPkg/RecipeRepos/com.github.fuzzylogiq.autopkg-recipes"
  alias cdapkg="cd $HOME/Library/AutoPkg/RecipeRepos/com.github.fuzzylogiq.autopkg-recipes" 
  alias udid="system_profiler SPHardwareDataType | awk '/Hardware UUID:/ {print \$3}'"
  alias ip='ifconfig en0 | awk '\''/inet/ { print $2 }'\'''

  # Functions
  function autoaamporter(){
     # Automatically builds a command line of plists to provide
     # to aamporter.py
     ls /srv/munki/aamporter/Adobe* | sed 's/^/-p /' | \
        xargs -J % /srv/munki/aamporter/aamporter.py \
        --munkiimport % --make-catalogs
  }
  function manana () {
    if [ -z $1 ]; then
      udid=$(udid)
    else
      udid=$(curl --silent -H "Authorization: Basic YXBpcmVhZG9ubHk6a0xrRXhTVlRtOTBzY0QK" https://jss.orchard.ox.ac.uk/JSSResource/computers/name/"$1" | xmllint --xpath "//computer/general/udid/text()" -)
    fi
	curl -H "Authorization: Basic b3JjaGFyZDpMKjQpWEd6RHRiRWo1NTJZ" https://munki.orchard.ox.ac.uk/production/manifests/${udid}
}

  function xpkg () {
    pkgutil --expand ${1} ${1%.*}
  }

fi

if [[ $SYSTYPE == "Linux" ]]; then
  # Subversion
  svn="$HOME/svn" 
fi

# vi editing mode
bindkey -v

# aliases
# SSH
if [ -f ~/.sshconfig ]; then
  alias ssh="~/.sshconfig && ssh"
fi
alias ss="ssh stelmaria"
alias sa="ssh adanac"

# Vim
alias vs="vi $HOME/.ssh/config"
alias vv="vi $HOME/.vimrc"
alias vz="vi $HOME/.zshrc"
alias vimnt="vim --cmd \"let g:templates_no_autocmd=1\""

# Autopkg
alias cdrep="cd $HOME/Library/AutoPkg/RecipeRepos/com.github.fuzzylogiq.autopkg-recipes"
alias cdapkg="cd $HOME/Library/AutoPkg/RecipeRepos/com.github.fuzzylogiq.autopkg-recipes"
alias sua="sudo -u autopkg"


alias pg="ping www.google.co.uk"
alias history="history 1"


if [ -n "$svn" ]; then
  alias cdpup="cd $svn/nsms/config/puppet"
  alias cdsvn="cd $svn/nsms"
  alias cdmmp="cd $svn/nsms/src/n/nsms-mmp-scripts/trunk/"
  alias cdvip="cd $svn/nsms/config/network/vip-firewalls"
  alias cdans="cd $svn/nsms/scratch/ben/ansible/orchard_infrastructure"
fi


# functions
hex() {
  python -c "print hex($1)"
}

spurt() {
  [ -z "$2" ] && port="443" || port="$2"
  echo | \
    openssl s_client -host "$1" -port "${port}" 2>&1 | \
    sed '/-----BEGIN CERTIFICATE-----/,$!d;/-----END CERTIFICATE-----/q' | \
    openssl x509 -in /dev/stdin -noout -text
}

valid() {
  spurt ${@} | awk '/Validity/ {for(i=0;i<2;i++)  { getline; sub(/^[ \t]+/, ""); print }}'
}

# zstyle completion options
zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*' group-name ''

setopt nobeep

# iTerm shell integration
test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh
alias vnt='vim --cmd "let g:templates_no_autocmd=1"'

# Perlbrew
#source ~/perl5/perlbrew/etc/bashrc
alias config='/usr/bin/git --git-dir=/Users/ouit0354/.cfg/ --work-tree=/Users/ouit0354'
source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export LC_COLLATE="en_GB.UTF-8"
export LC_CTYPE="en_GB.UTF-8"
export LC_MESSAGES="en_GB.UTF-8"
export LC_MONETARY="en_GB.UTF-8"
export LC_NUMERIC="en_GB.UTF-8"
export LC_TIME="en_GB.UTF-8"
export LC_ALL="en_GB.UTF-8"

