#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# system specific stuff
SYSTYPE=$(uname)

# mac os x specific stuff
if [[ $SYSTYPE == "Darwin" ]]; then
  if [ -d "$HOME/Developer/homebrew/bin" ]; then
    PATH="$HOME/Developer/homebrew/bin:$HOME/bin:$PATH"
    vimversion=$(ls -r $HOME/Developer/homebrew/Cellar/vim | head -n 1)
    export VIMRUNTIME="$HOME/Developer/homebrew/Cellar/vim/${vimversion}/share/vim/vim74"
    [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh
  fi
  
  svn="$HOME/Developer/svn"
  alias plx='plutil -convert xml1 -o -'
  
  alias cdrep="cd $HOME/Library/AutoPkg/RecipeRepos/com.github.fuzzylogiq.autopkg-recipes"
  alias cdapkg="cd $HOME/Library/AutoPkg/RecipeRepos/com.github.fuzzylogiq.autopkg-recipes"
  
  function autoaamporter(){
     # Automatically builds a command line of plists to provide
     # to aamporter.py
     ls /srv/munki/aamporter/Adobe* | sed 's/^/-p /' | \
        xargs -J % /srv/munki/aamporter/aamporter.py \
        --munkiimport % --make-catalogs
  }
fi

if [[ $SYSTYPE == "Linux" ]]; then
  :
fi

# vi editing mode
bindkey -v

# aliases
alias ss="ssh stelmaria"
alias sa="ssh adanac"
alias vs="vi $HOME/.ssh/config"
alias vv="vi $HOME/.vimrc"
alias vz="vi $HOME/.zshrc"

alias sua="sudo -u autopkg"
alias pg="ping www.google.co.uk"
alias history="history 1"
if [ -f ~/.sshconfig ]; then
  alias ssh="~/.sshconfig && ssh"
fi

if [ -n "$svn" ]; then
  alias cdpup="cd $svn/nsms/config/puppet"
  alias cdsvn="cd $svn/nsms"
  alias cdmmp="cd $svn/nsms/src/n/nsms-mmp-scripts/trunk/"
  alias cdvip="cd $svn/nsms/config/network/vip-firewalls"
fi

# zstyle completion options
zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*' group-name ''

setopt nobeep

# iTerm shell integration
test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh
